name: Build project and deploy on Firebase Hosting
'on':
  push:
    branches:
      - production
jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm ci
      - name: Build
        run: npm run buildpro
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TIME_SHEET_9B403 }}'
          channelId: live
          projectId: time-sheet-9b403
